### ISSUE TITLE
TAVOSS-TR:Django

### ISSUE THREAD

**Issue by asa1997** [Be-Secure/BeSLighthouse#113]
### Version of the project

4.0.3

### Tech Stack

Language and Framwork [L&F]

### Project details

Django is an open source full stack framework from python

### Languages used

Python

### Domain

Technology

### Industry

All

### Open Source Project type

Community led

### Repo URL

https://github.com/django/django

### Webpage

https://www.djangoproject.com/

### License

others

### Other license

Copyright - Django Software Foundation

**Comment by sumodgeorge** [comment]
Approved and close the issue
