### ISSUE TITLE
TAVOSS-TR:Spring-security

### ISSUE THREAD

**Issue by jobyko** [Be-Secure/BeSLighthouse#37]
### Version of the project

5.6.0-M1 

### Tech Stack

Application [A]

### Project details

Spring Security provides security services for the Spring IO Platform

### Languages used

Java

### Domain

Both

### Industry

All

### Open Source Project type

Community led

### Repo URL

https://github.com/spring-projects/spring-security

### Webpage

https://spring.io/

### License

Apache-2.0

### Why we should track it.

Spring Security provides security services for the Spring IO Platform

**Comment by sumodgeorge** [comment]
This project is accepted for tracking hence closing this issue with status as Tracked
