### ISSUE TITLE
TAVOSS-TR:Springfox

### ISSUE THREAD

**Issue by jobyko** [Be-Secure/BeSLighthouse#38]
### Version of the project

3

### Tech Stack

Application [A]

### Project details

Automated JSON API documentation for API's built with Spring

### Languages used

Java, Groovy

### Domain

Technology

### Industry

All

### Open Source Project type

Community led

### Repo URL

https://github.com/springfox/springfox

### Webpage

http://springfox.github.io/springfox/

### License

Apache-2.0

### Why we should track it.

Automated JSON API documentation for API's built with Spring

**Comment by sumodgeorge** [comment]
This project is accepted for tracking hence closing this issue with status as Tracked
