### ISSUE TITLE
TAVOSS-TR:Portus

### ISSUE THREAD

**Issue by jobyko** [Be-Secure/BeSLighthouse#39]
### Version of the project

2.4.3

### Tech Stack

Application [A]

### Project details

It is an authorization server and a user interface for the next generation of the Docker registry. Portus targets version 2 of the Docker Registry API

### Languages used

Ruby, Vue 

### Domain

Technology

### Industry

All

### Open Source Project type

Community led

### Repo URL

https://github.com/SUSE/Portus

### Webpage

http://port.us.org/

### License

Apache-2.0

### Why we should track it.

It is an authorization server and a user interface for the next generation of the Docker registry. Portus targets version 2 of the Docker Registry API

**Comment by sumodgeorge** [comment]
This project is accepted for tracking hence closing this issue with status as Tracked
