### ISSUE TITLE
TAVOSS-TR:PHP-PM 

### ISSUE THREAD

**Issue by jobyko** [Be-Secure/BeSLighthouse#40]
### Version of the project

2.2.2

### Tech Stack

Application [A]

### Project details

PHP-PM is a process manager, supercharger and load balancer for PHP applications.

### Languages used

PHP

### Domain

Technology

### Industry

All

### Open Source Project type

Community led

### Repo URL

https://github.com/php-pm/php-pm

### Webpage

https://web.archive.org/web/20190103202024/http://marcjschmidt.de/2014/02/08/php-high-performance/

### License

MIT

### Why we should track it.

PHP-PM is a process manager, supercharger and load balancer for PHP applications. Some of its features like hot code reloading supports development activities seamlessly.

**Comment by sumodgeorge** [comment]
This project is accepted for tracking hence closing this issue with status as Tracked
