### ISSUE TITLE
TAVOSS-TR:Grav

### ISSUE THREAD

**Issue by jobyko** [Be-Secure/BeSLighthouse#41]
### Version of the project

1.7.18

### Tech Stack

Application [A]

### Project details

Grav is a Fast, Simple, and Flexible, file-based Web-platform. There is Zero installation required. Just extract the ZIP archive, and you are already up and running. It follows similar principles to other flat-file CMS platforms, but has a different design philosophy than most. Grav comes with a powerful Package Management System to allow for simple installation and upgrading of plugins and themes, as well as simple updating of Grav itself.

### Languages used

PHP

### Domain

Technology

### Industry

All

### Open Source Project type

Community led

### Repo URL

https://github.com/getgrav/grav

### Webpage

https://getgrav.org/downloads

### License

MIT

### Why we should track it.

Grav is a Fast, Simple, and Flexible, file-based Web-platform. There is Zero installation required. Just extract the ZIP archive, and you are already up and running. It follows similar principles to other flat-file CMS platforms, but has a different design philosophy than most. Grav comes with a powerful Package Management System to allow for simple installation and upgrading of plugins and themes, as well as simple updating of Grav itself.

**Comment by sumodgeorge** [comment]
This project is accepted for tracking hence closing this issue with status as Tracked
