### ISSUE TITLE
TAVOSS-TR:Wallabag

### ISSUE THREAD

**Issue by jobyko** [Be-Secure/BeSLighthouse#42]
### Version of the project

2.4.2

### Tech Stack

Application [A]

### Project details

wallabag is a self-hostable PHP application allowing you to not miss any content anymore. Click, save and read it when you can. It extracts content so that you can read it when you have time.

### Languages used

PHP

### Domain

Technology

### Industry

All

### Open Source Project type

Community led

### Repo URL

https://github.com/wallabag/wallabag

### Webpage

https://wallabag.org/en

### License

MIT

### Why we should track it.

wallabag is a self-hostable PHP application allowing you to not miss any content anymore. Click, save and read it when you can. It extracts content so that you can read it when you have time.

**Comment by sumodgeorge** [comment]
This project is accepted for tracking hence closing this issue with status as Tracked
