### ISSUE TITLE
TAVOSS-TR:Joplin

### ISSUE THREAD

**Issue by jobyko** [Be-Secure/BeSLighthouse#44]
### Version of the project

server-v2.2.11-beta

### Tech Stack

Application [A]

### Project details

Joplin is a free, open source note taking and to-do application, which can handle a large number of notes organised into notebooks. The notes are searchable, can be copied, tagged and modified either from the applications directly or from your own text editor.

### Languages used

TypeScript, JavaScript

### Domain

Technology

### Industry

Education

### Open Source Project type

Community led

### Repo URL

https://github.com/laurent22/joplin

### Webpage

https://discourse.joplinapp.org/

### License

MIT

### Why we should track it.

Joplin is a free, open source note taking and to-do application, which can be customized for end-user consumption.

**Comment by sumodgeorge** [comment]
This project is accepted for tracking hence closing this issue with status as Tracked
