### ISSUE TITLE
TAVOSS-TR:Bit

### ISSUE THREAD

**Issue by jobyko** [Be-Secure/BeSLighthouse#45]
### Version of the project

v14.8.9-server.1

### Tech Stack

Application [A]

### Project details

Bit is an open-source toolchain for composing modern applications from independent components. 

### Languages used

TypeScript

### Domain

Technology

### Industry

All

### Open Source Project type

Community led

### Repo URL

https://github.com/teambit/bit

### Webpage

https://harmony-docs.bit.dev/

### License

Apache-2.0

### Why we should track it.

Bit is an open-source toolchain for composing modern applications from independent components.

**Comment by sumodgeorge** [comment]
This project is accepted for tracking hence closing the issue with status Tracked
