### ISSUE TITLE
TAVOSS-TR:Espocrm

### ISSUE THREAD

**Issue by jobyko** [Be-Secure/BeSLighthouse#46]
### Version of the project

6.1.8

### Tech Stack

Application [A]

### Project details

EspoCRM is an Open Source CRM (Customer Relationship Management) software that allows you to see, enter and evaluate all your company relationships regardless of the type. People, companies or opportunities - all in an easy and intuitive interface.

### Languages used

PHP, JavaScript

### Domain

Technology

### Industry

All

### Open Source Project type

Community led

### Repo URL

https://github.com/espocrm/espocrm

### Webpage

https://www.espocrm.com/

### License

GPL-3.0

### Why we should track it.

EspoCRM is an Open Source CRM (Customer Relationship Management) software that allows you to see, enter and evaluate all your company relationships regardless of the type. People, companies or opportunities - all in an easy and intuitive interface.

**Comment by sumodgeorge** [comment]
This project is accepted for tracking hence closing this issue with status as Tracked
