### ISSUE TITLE
TAVOSS-TR:Pimcore

### ISSUE THREAD

**Issue by jobyko** [Be-Secure/BeSLighthouse#47]
### Version of the project

v10.1.0

### Tech Stack

Application [A]

### Project details

Pimcore - Open Source Data & Experience Management Platform: PIM, MDM, CDP, DAM, DXP/CMS & Digital Commerce

### Languages used

PHP, JavaScript

### Domain

Technology

### Industry

All

### Open Source Project type

Community led

### Repo URL

https://github.com/pimcore/pimcore

### Webpage

https://pimcore.com/en

### License

GPL-3.0

### Why we should track it.

Pimcore offers ability to manage data objects, digital assets and documents for application very effectively

**Comment by sumodgeorge** [comment]
This project is accepted for tracking hence closing this issue with status as Tracked.
