### ISSUE TITLE
TAVOSS-TR:Prometheus

### ISSUE THREAD

**Issue by asa1997** [Be-Secure/BeSLighthouse#50]
### Version of the project

v2.29.0-rc.0

### Tech Stack

DevOps [DO]

### Project details

Prometheus, a Cloud Native Computing Foundation project, is a systems and service monitoring system. It collects metrics from configured targets at given intervals, evaluates rule expressions, displays the results, and can trigger alerts when specified conditions are observed.

### Languages used

GO

### Domain

Security

### Industry

All

### Open Source Project type

Foundation led

### Repo URL

https://github.com/prometheus/prometheus

### Webpage

https://prometheus.io/

### License

Apache-2.0

### Why we should track it.

The features that distinguish Prometheus from other metrics and monitoring systems are:

- A multi-dimensional data model (time series defined by metric name and set of key/value dimensions)
- PromQL, a powerful and flexible query language to leverage this dimensionality
- No dependency on distributed storage; single server nodes are autonomous
- An HTTP pull model for time series collection
- Pushing time series is supported via an intermediary gateway for batch jobs
- Targets are discovered via service discovery or static configuration
- Multiple modes of graphing and dashboarding support
- Support for hierarchical and horizontal federation

**Comment by sumodgeorge** [comment]
This project is accepted for tracking hence closing the issue with status Tracked
