### ISSUE TITLE
POI landing page revamp with filters

### ISSUE THREAD

**Issue by harimohanr** [Be-Secure/BeSLighthouse#502]
Projects of Interest (POI)
- Show the total projects count
- Implement a filter on the projects list based on the tags
- Remove the pie charts from POI screen and show the percentages only. This is to get more space in the page. In technology stack, show the full form for each tech stack (ex: Instead of DO, show DevOps)
- In the projects table, show the full form for BeSTechStack

<img width="1080" alt="Screenshot 2024-01-03 at 11 28 56 AM" src="https://github.com/Be-Secure/BeSLighthouse/assets/30436665/61cfc67a-7b6d-443e-8edb-ba840bbb7432">

**Comment by asa1997** [comment]
Closed with #564
