### ISSUE TITLE
[Bug]: Incorrect redirect from force directed graph on moi page

### ISSUE THREAD

**Issue by asa1997** [Be-Secure/BeSLighthouse#506]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://be-secure.github.io/Be-Secure/contribute.html) and wholeheartedly agree

### Description

The projects listed in the force directed graph is taking users to a different url.

### Expected behaviour

Should take users to model card page.

### Actual behaviour

Is taking users to different page

### Steps to reproduce

1. Go to https://be-secure.github.io/BeSLighthouse/Model-Of-Interest
2. Switch view to force directed graph.
3. Select a project.

### Relevant screenshots

NA

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by pramit-d** [comment]
https://github.com/Be-Secure/BeSLighthouse/pull/510 merged.
