### ISSUE TITLE
[Bug]: Unable to open few ml models from force directed graph in moi page

### ISSUE THREAD

**Issue by asa1997** [Be-Secure/BeSLighthouse#507]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://be-secure.github.io/Be-Secure/contribute.html) and wholeheartedly agree

### Description

The below ml models cannot be opened from force directed graph
1. bes-image-classification
2. Image_Segmentation
3. Tabular_Classification
4. Timeseries_Forecasting

### Expected behaviour

on click should take it to their respective model card page

### Actual behaviour

disabled

### Steps to reproduce

1. Go to https://be-secure.github.io/BeSLighthouse/Model-Of-Interest
2. Try to select any of the mentioned projects.

### Relevant screenshots

NA

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
api.nepcha.com/api/v1/send-event:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
api.nepcha.com/api/v1/send-event:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
nepcha-analytics.js:6  Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at HTMLDocument.<anonymous> (nepcha-analytics.js:6:1828)
api.nepcha.com/api/v1/send-event:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
api.nepcha.com/api/v1/send-event:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
api.nepcha.com/api/v1/send-event:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
api.nepcha.com/api/v1/send-event:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
Model-Of-Interest:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by pramit-d** [comment]
![Screenshot from 2024-01-03 10-36-07](https://github.com/Be-Secure/BeSLighthouse/assets/125947785/30b996c8-7146-4c08-b222-f0593cbd8340)
**model_card** url is not available for the above mentioned models, so the click functionality is disabled by the code.

**Comment by asa1997** [comment]
@pramit-d Please fix the issue and mention the pr before closing.

**Comment by pramit-d** [comment]
https://github.com/Be-Secure/BeSLighthouse/pull/510 merged.
