### ISSUE TITLE
MOI landing page revamp with filters

### ISSUE THREAD

**Issue by harimohanr** [Be-Secure/BeSLighthouse#508]
Models of Interest (POI)
- Show the models count
- Implement a filter on the models list based on the tags
- Remove the pie charts from MOI screen and show the percentages only. This is to get more space in the page.
<img width="1085" alt="Screenshot 2024-01-03 at 11 26 40 AM" src="https://github.com/Be-Secure/BeSLighthouse/assets/30436665/fa51744f-418e-4bac-bc4e-1a9b1d92b3d7">

**Comment by asa1997** [comment]
Issue has been resolved on a previous release
