### ISSUE TITLE
Discrepancy in color shades used in pie charts

### ISSUE THREAD

**Issue by sumodgeorge** [Be-Secure/BeSLighthouse#528]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://be-secure.github.io/Be-Secure/contribute.html) and wholeheartedly agree

### Description

On the Projects of Interest landing page, same color shade has been used to represent multiple entities in the pie chart. Not being able to map the entity values to the pie chart. 

### Expected behaviour

The pie chart should use different shades that are distinguishable to reflect each distinct entity on the chart.

### Actual behaviour

Same color shade is used to reflect data for two entities on the pie chart.

### Steps to reproduce

It is very much visible on the landing page for Projects of Interest.

### Relevant screenshots

Note able to attach screen shot

**Comment by asa1997** [comment]
Fixed by @sudhirverma.

![image](https://github.com/Be-Secure/BeSLighthouse/assets/58501088/5f10daeb-77b1-402b-b87d-9dd2933fb607)
