### ISSUE TITLE
Write up on POI page and VOI page

### ISSUE THREAD

**Issue by sumodgeorge** [Be-Secure/BeSLighthouse#529]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://be-secure.github.io/Be-Secure/contribute.html) and wholeheartedly agree

### Description

The POI and VOI pages don't have any write up to explain the purpose of these pages and what the user can view in these pages.

### Expected behaviour

A write up depicting the purpose of the respective page ( one for POI and other for VOI) will help the end user have better understanding on the relevance of these pages.  Also include a statement on how to use these pages.

### Actual behaviour

This is an enhancement request

### Steps to reproduce

NA

### Relevant screenshots

NA

**Comment by sudhirverma** [comment]
Fixed in last release
