### ISSUE TITLE
[Bug]:Risk color indicators are displaying behind the risk posture pie chart in POI project card

### ISSUE THREAD

**Issue by pramit-d** [Be-Secure/BeSLighthouse#535]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://be-secure.github.io/Be-Secure/contribute.html) and wholeheartedly agree

### Description

**low, medium, high, critical** color indicators are displaying behind the risk posture pie chart in POI project card.

### Expected behaviour

It should be below the risk posture pie chart.

### Actual behaviour

**low, medium, high, critical** color indicators are displaying behind the risk posture pie chart.

### Steps to reproduce

1. Open BeSlighthouse website.
2. click on project of interest page.
3. open **fastjson**  or any project card.
4. scroll down to risk posture pie chart.

### Relevant screenshots

![Screenshot from 2024-01-12 21-02-12](https://github.com/Be-Secure/BeSLighthouse/assets/125947785/dcb413cb-bba1-4798-a632-75d499d8da11)

### What browsers are you seeing the problem on?

Firefox

**Comment by asa1997** [comment]
done
