### ISSUE TITLE
[Bug]: Broken css for pie chart under project details

### ISSUE THREAD

**Issue by asa1997** [Be-Secure/BeSLighthouse#544]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://be-secure.github.io/Be-Secure/contribute.html) and wholeheartedly agree

### Description

The css for pie chart under project details section is broken.

### Expected behaviour

The pie chart should be displayed properly.

### Actual behaviour

The chart overlaps with its legend.

### Steps to reproduce

NA

### Relevant screenshots

![image](https://github.com/Be-Secure/BeSLighthouse/assets/58501088/fca5a39c-6088-45e7-b97d-0567c6ce1df6)

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by sudhirverma** [comment]
done
