### ISSUE TITLE
[Bug]: Missing sanity check on link to BeS environment scripts from project card

### ISSUE THREAD

**Issue by asa1997** [Be-Secure/BeSLighthouse#545]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://be-secure.github.io/Be-Secure/contribute.html) and wholeheartedly agree

### Description

The environment script link under each project card is active irrespective of whether the scipts are available or not.

### Expected behaviour

Should display "not available"

### Actual behaviour

Displays a link

### Steps to reproduce

NA

### Relevant screenshots

NA

### What browsers are you seeing the problem on?

Chrome

**Comment by pramit-d** [comment]
#554 merged.
