### ISSUE TITLE
[Bug]: Discrepancy in License compatibility for wagtail

### ISSUE THREAD

**Issue by sumodgeorge** [Be-Secure/BeSLighthouse#546]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://be-secure.github.io/Be-Secure/contribute.html) and wholeheartedly agree

### Description

The project license for wagtail is shown as bsd-3-clause while License compatibility is shown as 0 in the project details page

### Expected behaviour

The license compatibility should reflect the unique count of licenses identified within the project and its dependency files.

### Actual behaviour

Though a license has been identified yet the license compatibility is shown as 0

### Steps to reproduce

Can we viewed in the project details page for wagtail project with version 2.14.

### Relevant screenshots

Will upload later

**Comment by sudhirverma** [comment]
Need to fix from assessment side.
