### ISSUE TITLE
[Enhancement] : Limit data to vulnerabilities details only while displaying count from Sonarqube in the SAST Analysis Summary

### ISSUE THREAD

**Issue by sumodgeorge** [Be-Secure/BeSLighthouse#552]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://be-secure.github.io/Be-Secure/contribute.html) and wholeheartedly agree

### Description

SAST report from Sonarqube is likely to include code smells and other issues apart from vulnerabilities. Need not account for the non vulnerability details in the SAST Analysis Summary section in the projects of interest details page.

### Expected behaviour

The SAST Summary analysis should reflect the split up of vulnerabilities based on their severity levels from the Sonarqube report. Other count need not be accounted here in this section.

### Actual behaviour

For Indy-node project, under the SAST Summary Analysis section, the count for Sonarqube is shown as 2078 while the split up vulnerabilities in this section is shown as following  - High : 31; Medium : 11; Low : 56. This doesn't align with 2078 value shown in the same section.

### Steps to reproduce

Can be viewed while visiting the Project of Interest details page for Indy-node.

### Relevant screenshots

Will be uploaded later

**Comment by sudhirverma** [comment]
Fixed: #595
