### ISSUE TITLE
[Enhancement]: Revamping the project card page

### ISSUE THREAD

**Issue by asa1997** [Be-Secure/BeSLighthouse#575]
![project_card4](https://github.com/Be-Secure/BeSLighthouse/assets/58501088/479ac04e-ae66-4f55-806e-41ec4c4b8c19)

## Project details

1. The `OSAR`  is a download button which should be activated once the reports are available.
2. Add an appropriate icon next to the OSAR download button, which depicts the report has been attested.
3. The `Envs and Playbooks` is a button, which opens up a modal component with environments and compatible playbooks.
4. The `OSAP`(Open Source Assurance Provider) will show the name of the entity that performed the assessments, followed by an appropriate icon. The entity can be a user, an organization or a lab.
5. The tags and languages should be a link, on-click, it should trigger the filter for that tag/lang which updates the poi table.

## Assessment details

1. The scores and assessment counts are modal component which gives you a summary report of its respective assessment.
2. The `OWASP Top Vulnerability Type` should display the [OWASP top vulnerability types](https://owasp.org/Top10/) that the vulnerabilities from sast report belongs to.
3. The `Vulnerability Trend` gives you the count of vulnerabilities, for this version of the project, over the years.

**Comment by sudhirverma** [comment]
Fixed in previous release
