### ISSUE TITLE
[Bug]: Additional versions are listed for logstash project on the project details page

### ISSUE THREAD

**Issue by sumodgeorge** [Be-Secure/BeSLighthouse#579]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://be-secure.github.io/Be-Secure/contribute.html) and wholeheartedly agree

### Description

FOr logstash, version 8.6.1, 8.8.2 was identified for security risk assessment and the same has been completed. Currently in the version list down the following versions are displayed - 8.10.2 , 8.11.4. These are not the latest versions either.

### Expected behaviour

Display the versions for which there is some data available in the besecure-assessment-datastore. This is necessary till we implement the automation of risk assessment which will enable scalability.

### Actual behaviour

The following versions are also list 8.10.2, 8.11.4 for which no data is available.

### Steps to reproduce

List the versions in the details page

### Relevant screenshots

NA

### Relevant log output

```shell
NA
```

**Comment by sudhirverma** [comment]
Closing this issue as data available for logstash
