### ISSUE TITLE
TAVOSS-TR: Hygieia

### ISSUE THREAD

**Issue by asa1997** [Be-Secure/BeSLighthouse#58]
### Version of the project

Baseline version for UI only Hygieia Project

### Tech Stack

DevOps [DO]

### Project details

CapitalOne DevOps Dashboard.

The Hygieia Executive Dashboard enables senior leadership at your organization to understand the DevOps state of maturity and risk across a wide range of product portfolios. This macro view of product portfolios allows them leverage to set precise goals for improvements on DevOps maturity, risk, and maintaining consistency across the portfolio. It provides insights into areas such as:

- Key Performance Indicators (KPIs) for quality aggregated across team instances
- Enterprise-wide quality standards to measure SDLC maturity risk and compliance
- Incidence visibility for service at various severity levels in production
- Alerts for product standards across products in a portfolio
- Drives usage of standard DevOps toolsets

### Languages used

TypeScript

### Domain

Technology

### Industry

All

### Open Source Project type

Community led

### Repo URL

https://github.com/hygieia/hygieia

### Webpage

https://hygieia.github.io/ExecDashboard/Introduction.html

### License

Apache-2.0

### Reason , why we must track this project.

Hygieia’s dashboards simplify the ability to view CICD pipelines in near real-time. The dashboards enable DevOps engineers and executives to monitor the health of code commit to deployment in final production. Between those two points – inception (commit) to completion (prod) – the dashboards also provide crucial information about the overall vitality and performance metrics of your software operations.

**Comment by sumodgeorge** [comment]
This project is accepted for tracking hence closing this issue with status tracked.
