### ISSUE TITLE
[Bug]: Incorrect sonarqube data displaying for spring-data-mongodb

### ISSUE THREAD

**Issue by pramit-d** [Be-Secure/BeSLighthouse#586]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://be-secure.github.io/Be-Secure/contribute.html) and wholeheartedly agree

### Description

In the project card, **High** count is 1 but no issues are available in json report.

### Expected behaviour

NA

### Actual behaviour

NA

### Steps to reproduce

NA

### Relevant screenshots

![Screenshot from 2024-02-15 11-42-03](https://github.com/Be-Secure/BeSLighthouse/assets/125947785/60197427-0766-4945-8cb4-36b45ad653ca)

**Comment by sudhirverma** [comment]
Closing this issue as fixed in previous release
