### ISSUE TITLE
TAVOSS-TR:Kafka

### ISSUE THREAD

**Issue by asa1997** [Be-Secure/BeSLighthouse#60]
### Version of the project

2.8.1-rc0

### Tech Stack

DevOps [DO]

### Project details

Apache Kafka is an open-source distributed event streaming platform used for high-performance data pipelines, streaming analytics, data integration, and mission-critical applications.

### Languages used

Java

### Domain

Both

### Industry

All

### Open Source Project type

Community led

### Repo URL

https://github.com/apache/kafka

### Webpage

https://kafka.apache.org/

### License

Apache-2.0

### Reason , why we must track this project.

- HIGH THROUGHPUT
   Deliver messages at network limited throughput using a cluster of machines with latencies as low as 2ms.

-  SCALABLE
   Scale production clusters up to a thousand brokers, trillions of messages per day, petabytes of data, hundreds of 
  thousands of partitions. Elastically expand and contract storage and processing.

- PERMANENT STORAGE
   Store streams of data safely in a distributed, durable, fault-tolerant cluster.
  
- HIGH AVAILABILITY
   Stretch clusters efficiently over availability zones or connect separate clusters across geographic regions.

**Comment by sumodgeorge** [comment]
This project is accepted for tracking hence closing this issue with status as Tracked.
