### ISSUE TITLE
TAVOSS-TR:Captain Stack

### ISSUE THREAD

**Issue by asa1997** [Be-Secure/BeSLighthouse#63]
### Version of the project

NA

### Tech Stack

DevOps [DO]

### Project details

VSCode extension for code suggestion

### Languages used

GO

### Domain

Technology

### Industry

All

### Open Source Project type

Others

### Repo URL

https://github.com/hieunc229/copilot-clone

### License

MIT

**Comment by sumodgeorge** [comment]
This project can be considered later on after assessing it further to understand the distinct capabilities it offers hence closing this issue.
