### ISSUE TITLE
[Bug]: CSS issue for model card page

### ISSUE THREAD

**Issue by asa1997** [Be-Secure/BeSLighthouse#635]
![Screenshot_2024-06-18-18-24-18-30_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://github.com/Be-Secure/BeSLighthouse/assets/58501088/a4cbb1a1-d9eb-48ab-8981-5da9908e2936)

**Comment by sudhirverma** [comment]
Closing this issue as new UI has been introduce.
