### ISSUE TITLE
TODO: TAVOSS-TR templates support capturing additional details like tags 

### ISSUE THREAD

**Issue by panickervinod** [Be-Secure/BeSLighthouse#64]
TAVOSS-TR template can also optionally support "tags"  to classify the OSSP, Please refer to #53  
However the tags must be validated during in the Request approval process.

//Tags applicable based on different Domain  
// 1. Industry : IND, 
// 2. Security Domain: SD, 
// 3. Community: COM, 
 // 4. Technology Usage: TD-U, 
 //5.  Technology Components and/or Composition :  TD-C

**Comment by sumodgeorge** [comment]
We had discussed this last week and then decided to not to use this in the request template as this is something we would need to review and assign before approving the request. We can add the tags once we approve the request.

**Comment by panickervinod** [comment]
Only closed request will be considered as approved and accepted.  However it is also good to capture what the requester believes it is , you should explicitly call out entering data for five tags is optional and have an information link with a questionnaire  & description of legends to help update the TR template .
