### ISSUE TITLE
TAVOSS-TR:Helm

### ISSUE THREAD

**Issue by asa1997** [Be-Secure/BeSLighthouse#68]
### Version of the project

Helm 3.6.3

### Tech Stack

DevOps [DO]

### Project details

Helm is a tool for managing Charts. Charts are packages of pre-configured Kubernetes resources

### Languages used

GO

### Domain

Technology

### Industry

All

### Open Source Project type

Foundation led

### Repo URL

https://github.com/helm/helm

### Webpage

https://helm.sh/

### License

Apache-2.0

### Reason , why we must track this project.

**Manage Complexity**

Charts describe even the most complex apps, provide repeatable application installation, and serve as a single point of authority.

**Easy Updates**

Take the pain out of updates with in-place upgrades and custom hooks.

**Simple Sharing**

Charts are easy to version, share, and host on public or private servers.

**Rollbacks**

Use helm rollback to roll back to an older version of a release with ease.

**Comment by sumodgeorge** [comment]
This project is accepted for tracking hence closing this issue with status Tracked.
