### ISSUE TITLE
TAVOSS-TR:Molecule 

### ISSUE THREAD

**Issue by asa1997** [Be-Secure/BeSLighthouse#69]
### Version of the project

3.4.0

### Tech Stack

DevOps [DO]

### Project details

Molecule project is designed to aid in the development and testing of Ansible roles.

Molecule provides support for testing with multiple instances, operating systems and distributions, virtualization providers, test frameworks and testing scenarios.

Molecule encourages an approach that results in consistently developed roles that are well-written, easily understood and maintained.

### Languages used

GO

### Industry

All

### Open Source Project type

Community led

### Repo URL

https://github.com/ansible-community/molecule

### Webpage

https://molecule.readthedocs.io/en/latest/

### License

MIT

**Comment by sumodgeorge** [comment]
Closing this issue request as it is duplicate
