### ISSUE TITLE
TAVOSS-TR: postgres

### ISSUE THREAD

**Issue by jobyko** [Be-Secure/BeSLighthouse#86]
### Version of the project

REL_14_0

### Tech Stack

Application [A]

### Project details

PostgreSQL is an advanced object-relational database management system
that supports an extended subset of the SQL standard, including
transactions, foreign keys, subqueries, triggers, user-defined types
and functions.  

### Languages used

C, PLpgSQL, Perl, Yacc

### Domain

Technology

### Industry

All

### Open Source Project type

Community led

### Repo URL

https://github.com/Be-Secure/postgres

### Webpage

https://github.com/postgres/postgres

### License

others

### Other license

Portions Copyright

### Reason , why we must track this project.

PostgreSQL is an advanced object-relational database management system
that supports an extended subset of the SQL standard, including
transactions, foreign keys, subqueries, triggers, user-defined types
and functions.  This distribution also contains C language bindings.

**Comment by sumodgeorge** [comment]
This project is accepted for tracking hence closing this issue with status as Tracked
