### ISSUE TITLE
TAVOSS-TR:Ignite

### ISSUE THREAD

**Issue by jobyko** [Be-Secure/BeSLighthouse#89]
### Version of the project

0.10.0

### Tech Stack

DevOps [DO]

### Project details

Weave Ignite is an open source Virtual Machine (VM) manager with a container UX and built-in GitOps management.

Combines Firecracker MicroVMs with Docker / OCI images to unify containers and VMs.
Works in a GitOps fashion and can manage VMs declaratively and automatically like Kubernetes and Terraform.

### Languages used

Go, Roff, Shell

### Domain

Technology

### Industry

All

### Open Source Project type

Community led

### Repo URL

https://github.com/weaveworks/ignite

### Sub-project repo URL

NA

### Webpage

https://www.weave.works/blog/fire-up-your-vms-with-weave-ignite

### License

Apache-2.0

### Other license

NA

### Reason , why we must track this project.

Weave Ignite is an open source Virtual Machine (VM) manager with a container UX and built-in GitOps management.

Combines Firecracker MicroVMs with Docker / OCI images to unify containers and VMs.
Works in a GitOps fashion and can manage VMs declaratively and automatically like Kubernetes and Terraform.

**Comment by sumodgeorge** [comment]
This project is accepted for tracking hence closing this issue with status as Tracked.
