### ISSUE TITLE
TAVOSS-TR:weave

### ISSUE THREAD

**Issue by jobyko** [Be-Secure/BeSLighthouse#90]
### Version of the project

2.8.1

### Tech Stack

DevOps [DO]

### Project details

This repository contains Weave Net, the first product developed by Weaveworks, with over 8 million downloads to date. Weave Net enables you to get started with Docker clusters and portable apps in a fraction of the time required by other solutions.

### Languages used

Go, Shell, Makefile

### Domain

Technology

### Industry

All

### Open Source Project type

Community led

### Repo URL

https://github.com/weaveworks/weave

### Sub-project repo URL

NA

### Webpage

https://www.weave.works/

### License

Apache-2.0

### Other license

NA

### Reason , why we must track this project.
 Weave Net enables you to get started with Docker clusters and portable apps in a fraction of the time required by other solutions. It helps connect Docker containers across multiple hosts and enables their automatic discovery. It permits portable microservices-based applications having multiple docker containers to run from a single host or multiple hosts.

**Comment by sumodgeorge** [comment]
This project is accepted for tracking hence closing this issue with status as Tracked
