### ISSUE TITLE
TAVOSS-TR:scope

### ISSUE THREAD

**Issue by jobyko** [Be-Secure/BeSLighthouse#91]
### Version of the project

1.13.2

### Tech Stack

DevOps [DO]

### Project details

Weave Scope automatically generates a map of your application, enabling you to intuitively understand, monitor, and control your containerized, microservices-based application.

### Languages used

Go, JavaScript, Shell

### Domain

Technology

### Industry

All

### Open Source Project type

Community led

### Repo URL

https://github.com/weaveworks/scope

### Sub-project repo URL

NA

### Webpage

https://www.weave.works/oss/scope/

### License

Apache-2.0

### Other license

NA

### Reason , why we must track this project.

Weave Scope automatically generates a map of your application, enabling you to intuitively understand, monitor, and control your containerized, microservices-based application.

**Comment by sumodgeorge** [comment]
This project is accepted for tracking hence closing this issue with status as Tracked.
