### ISSUE TITLE
TAVOSS-TR:checkov

### ISSUE THREAD

**Issue by jobyko** [Be-Secure/BeSLighthouse#94]
### Version of the project

2.0.496

### Tech Stack

Open-source Security Tool [S]

### Project details

It scans cloud infrastructure provisioned using Terraform, Terraform plan, Cloudformation, Kubernetes, Dockerfile, Serverless or ARM Templates and detects security and compliance misconfigurations using graph-based scanning.

Checkov also powers Bridgecrew, the developer-first platform that codifies and streamlines cloud security throughout the development lifecycle. Bridgecrew identifies, fixes, and prevents misconfigurations in cloud resources and infrastructure-as-code files.

### Languages used

Python, HCL

### Domain

Both

### Industry

Cybersecurity

### Open Source Project type

Community led

### Repo URL

https://github.com/bridgecrewio/checkov

### Sub-project repo URL

NA

### Webpage

https://www.checkov.io/

### License

Apache-2.0

### Other license

NA

### Reason , why we must track this project.

It scans cloud infrastructure provisioned using Terraform, Terraform plan, Cloudformation, Kubernetes, Dockerfile, Serverless or ARM Templates and detects security and compliance misconfigurations using graph-based scanning.

Checkov also powers Bridgecrew, the developer-first platform that codifies and streamlines cloud security throughout the development lifecycle. Bridgecrew identifies, fixes, and prevents misconfigurations in cloud resources and infrastructure-as-code files.

**Comment by sumodgeorge** [comment]
The project is accepted for tracking hence closing this issue with status changed as Tracked
