### ISSUE TITLE
TAVOSS-TR:Drupal

### ISSUE THREAD

**Issue by jobyko** [Be-Secure/BeSLighthouse#99]
### Version of the project

9.3

### Tech Stack

Application [A]

### Project details

Drupal is content management software. It's used to make many of the websites and applications you use every day

### Languages used

PHP

### Domain

Technology

### Industry

All

### Open Source Project type

Community led

### Repo URL

https://github.com/drupal/drupal

### Sub-project repo URL

NA

### Webpage

https://drupal.org/project/drupal

### License

GPL-2.0

### Other license

NA

### Reason , why we must track this project.

Drupal is content management software. It's used to make many of the websites and applications you use every day

**Comment by sumodgeorge** [comment]
Accepted for tracking
